### ISSUE TITLE
iOS Support for Kotlin Multiplatform Library

### ISSUE THREAD

**Issue by 19Micha90** [jillesvangurp/overpass-kotlin-client#1]
Firstly, thank you for your work on the overpass-kotlin-client library. I'm currently developing a Kotlin Multiplatform Mobile (KMM) application targeting both Android and iOS platforms. I wanted to include your library in my project, but I noticed that it currently only supports JVM and JavaScript targets. Would it be possible to add support for iOS targets as well?

**Comment by jillesvangurp** [comment]
Should be possible. Unfortunately I don't have a good way to test any of this. But I was working on adding support on my kt-search project a few weeks ago. If you have time to port some of those changes over and do a PR, I could release it. Otherwise this is a bit low priority for me right now.

**Comment by 19Micha90** [comment]
Tanks for your fast reply. Unfortunately, I don't have a Mac at the moment as well. I'm just doing this as a hobby and wanted to get the IOS hardware when I have the app ready on the android side. But when I'm ready and I have a Mac, I'll get to work on it and would create a PR.

**Comment by jillesvangurp** [comment]
@19Micha90 I updated the build to support IOS. Unfortunately jitpack doesn't really work well for multiplatform builds so I am using our own public repository.
